# Generated by Django 2.2.1 on 2019-06-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_Articulo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_Articulo', models.CharField(max_length=50)),
                ('vr_Unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_Cliente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_Cliente', models.CharField(max_length=50)),
                ('dir_Cliente', models.CharField(max_length=50)),
                ('ciu_Cliente', models.CharField(max_length=50)),
                ('tel_Cliente', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit_Proveedor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_Proveedor', models.CharField(max_length=50)),
                ('dir_proveedor', models.CharField(max_length=50)),
                ('ciu_proveedor', models.CharField(max_length=50)),
                ('tel_proveedor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('no_Factura', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fech_Factura', models.DateField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jokersapp.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total_Detalle', models.DecimalField(decimal_places=2, max_digits=15)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jokersapp.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('no_compra', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fech_Compra', models.DateField(auto_now_add=True)),
                ('num_factura', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jokersapp.Articulo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jokersapp.Proveedor')),
            ],
        ),
    ]
