# Generated by Django 2.2.1 on 2019-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokersapp', '0002_detalle_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='articulo',
        ),
        migrations.AddField(
            model_name='compra',
            name='articulo',
            field=models.ManyToManyField(to='jokersapp.Articulo'),
        ),
    ]
